package Hibernate_Class;
// Generated Dec 8, 2022 4:21:35 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int idCliente;
     private String nombre;
     private String apellido;
     private Set prestamoses = new HashSet(0);
     private Set devolucioneses = new HashSet(0);

    public Cliente() {
    }
    
    public Cliente(int idCliente,String nombre, String apellido) {
        this.idCliente = idCliente;
        this.nombre = nombre;
        this.apellido = apellido;
    }

    public Cliente(int idCliente) {
        this.idCliente = idCliente;
    }
    
    public Cliente(int idCliente, String nombre, String apellido, Set prestamoses, Set devolucioneses) {
       this.idCliente = idCliente;
       this.nombre = nombre;
       this.apellido = apellido;
       this.prestamoses = prestamoses;
       this.devolucioneses = devolucioneses;
    }
   
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public Set getPrestamoses() {
        return this.prestamoses;
    }
    
    public void setPrestamoses(Set prestamoses) {
        this.prestamoses = prestamoses;
    }
    public Set getDevolucioneses() {
        return this.devolucioneses;
    }
    
    public void setDevolucioneses(Set devolucioneses) {
        this.devolucioneses = devolucioneses;
    }




}


