package Hibernate_Class;
// Generated Dec 8, 2022 4:21:35 PM by Hibernate Tools 4.3.1



/**
 * Devoluciones generated by hbm2java
 */
public class Devoluciones  implements java.io.Serializable {


     private int idDevolucion;
     private Cliente cliente;
     private Libros libros;
     private String fecha;

    public Devoluciones() {
    }

	
    public Devoluciones(int idDevolucion) {
        this.idDevolucion = idDevolucion;
    }
    public Devoluciones(int idDevolucion, Cliente cliente, Libros libros, String fecha) {
       this.idDevolucion = idDevolucion;
       this.cliente = cliente;
       this.libros = libros;
       this.fecha = fecha;
    }
   
    public int getIdDevolucion() {
        return this.idDevolucion;
    }
    
    public void setIdDevolucion(int idDevolucion) {
        this.idDevolucion = idDevolucion;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Libros getLibros() {
        return this.libros;
    }
    
    public void setLibros(Libros libros) {
        this.libros = libros;
    }
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }




}


