package Hibernate_Class;
// Generated Dec 8, 2022 4:21:35 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Libros generated by hbm2java
 */
public class Libros  implements java.io.Serializable {


     private int idLibro;
     private String nombre;
     private String autor;
     private String anno;
     private Integer estado;
     private Set devolucioneses = new HashSet(0);
     private Set prestamoses = new HashSet(0);

    public Libros() {
    }
    
    public Libros(int idLibro,String nombre,String autor,String anno,int estado) {
        this.idLibro = idLibro;
        this.nombre = nombre;
        this.autor = autor;
        this.anno = anno;
        this.estado = estado;
    }

    public Libros(int idLibro) {
        this.idLibro = idLibro;
    }
    public Libros(int idLibro, String nombre, String autor, String anno, Integer estado, Set devolucioneses, Set prestamoses) {
       this.idLibro = idLibro;
       this.nombre = nombre;
       this.autor = autor;
       this.anno = anno;
       this.estado = estado;
       this.devolucioneses = devolucioneses;
       this.prestamoses = prestamoses;
    }
   
    public int getIdLibro() {
        return this.idLibro;
    }
    
    public void setIdLibro(int idLibro) {
        this.idLibro = idLibro;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getAutor() {
        return this.autor;
    }
    
    public void setAutor(String autor) {
        this.autor = autor;
    }
    public String getAnno() {
        return this.anno;
    }
    
    public void setAnno(String anno) {
        this.anno = anno;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }
    public Set getDevolucioneses() {
        return this.devolucioneses;
    }
    
    public void setDevolucioneses(Set devolucioneses) {
        this.devolucioneses = devolucioneses;
    }
    public Set getPrestamoses() {
        return this.prestamoses;
    }
    
    public void setPrestamoses(Set prestamoses) {
        this.prestamoses = prestamoses;
    }




}


