package Hibernate_Class;
// Generated Dec 8, 2022 4:21:35 PM by Hibernate Tools 4.3.1



/**
 * Prestamos generated by hbm2java
 */
public class Prestamos  implements java.io.Serializable {


     private int idPrestamo;
     private Cliente cliente;
     private Libros libros;
     private String fecha;

    public Prestamos() {
    }

	
    public Prestamos(int idPrestamo) {
        this.idPrestamo = idPrestamo;
    }
    public Prestamos(int idPrestamo, Cliente cliente, Libros libros, String fecha) {
       this.idPrestamo = idPrestamo;
       this.cliente = cliente;
       this.libros = libros;
       this.fecha = fecha;
    }
   
    public int getIdPrestamo() {
        return this.idPrestamo;
    }
    
    public void setIdPrestamo(int idPrestamo) {
        this.idPrestamo = idPrestamo;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Libros getLibros() {
        return this.libros;
    }
    
    public void setLibros(Libros libros) {
        this.libros = libros;
    }
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }




}


