//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen.WS_Reference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaClienteResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ListaClienteResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellidoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idCliente {
            get {
                return this.idClienteField;
            }
            set {
                if ((this.idClienteField.Equals(value) != true)) {
                    this.idClienteField = value;
                    this.RaisePropertyChanged("idCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string apellido {
            get {
                return this.apellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.apellidoField, value) != true)) {
                    this.apellidoField = value;
                    this.RaisePropertyChanged("apellido");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaLibroResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ListaLibroResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idLibroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string autorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string annoField;
        
        private System.Nullable<int> estadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idLibro {
            get {
                return this.idLibroField;
            }
            set {
                if ((this.idLibroField.Equals(value) != true)) {
                    this.idLibroField = value;
                    this.RaisePropertyChanged("idLibro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string autor {
            get {
                return this.autorField;
            }
            set {
                if ((object.ReferenceEquals(this.autorField, value) != true)) {
                    this.autorField = value;
                    this.RaisePropertyChanged("autor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string anno {
            get {
                return this.annoField;
            }
            set {
                if ((object.ReferenceEquals(this.annoField, value) != true)) {
                    this.annoField = value;
                    this.RaisePropertyChanged("anno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<int> estado {
            get {
                return this.estadoField;
            }
            set {
                if ((this.estadoField.Equals(value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaPrestamosResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ListaPrestamosResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idPrestamoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fechaField;
        
        private System.Nullable<int> idClienteField;
        
        private System.Nullable<int> idlibroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idPrestamo {
            get {
                return this.idPrestamoField;
            }
            set {
                if ((this.idPrestamoField.Equals(value) != true)) {
                    this.idPrestamoField = value;
                    this.RaisePropertyChanged("idPrestamo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((object.ReferenceEquals(this.fechaField, value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<int> idCliente {
            get {
                return this.idClienteField;
            }
            set {
                if ((this.idClienteField.Equals(value) != true)) {
                    this.idClienteField = value;
                    this.RaisePropertyChanged("idCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<int> idlibro {
            get {
                return this.idlibroField;
            }
            set {
                if ((this.idlibroField.Equals(value) != true)) {
                    this.idlibroField = value;
                    this.RaisePropertyChanged("idlibro");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaDevolucionesResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ListaDevolucionesResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idDevolucionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fechaField;
        
        private System.Nullable<int> idClienteField;
        
        private System.Nullable<int> idlibroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idDevolucion {
            get {
                return this.idDevolucionField;
            }
            set {
                if ((this.idDevolucionField.Equals(value) != true)) {
                    this.idDevolucionField = value;
                    this.RaisePropertyChanged("idDevolucion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((object.ReferenceEquals(this.fechaField, value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<int> idCliente {
            get {
                return this.idClienteField;
            }
            set {
                if ((this.idClienteField.Equals(value) != true)) {
                    this.idClienteField = value;
                    this.RaisePropertyChanged("idCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<int> idlibro {
            get {
                return this.idlibroField;
            }
            set {
                if ((this.idlibroField.Equals(value) != true)) {
                    this.idlibroField = value;
                    this.RaisePropertyChanged("idlibro");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS_Reference.WSSoap")]
    public interface WSSoap {
        
        // CODEGEN: Generating message contract since element name nombre from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/creaCliente", ReplyAction="*")]
        Examen.WS_Reference.creaClienteResponse creaCliente(Examen.WS_Reference.creaClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/creaCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<Examen.WS_Reference.creaClienteResponse> creaClienteAsync(Examen.WS_Reference.creaClienteRequest request);
        
        // CODEGEN: Generating message contract since element name NameEdit from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/editaCliente", ReplyAction="*")]
        Examen.WS_Reference.editaClienteResponse editaCliente(Examen.WS_Reference.editaClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/editaCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<Examen.WS_Reference.editaClienteResponse> editaClienteAsync(Examen.WS_Reference.editaClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminaCliente", ReplyAction="*")]
        bool eliminaCliente(int idCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminaCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> eliminaClienteAsync(int idCliente);
        
        // CODEGEN: Generating message contract since element name MostrarClientesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MostrarClientes", ReplyAction="*")]
        Examen.WS_Reference.MostrarClientesResponse MostrarClientes(Examen.WS_Reference.MostrarClientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MostrarClientes", ReplyAction="*")]
        System.Threading.Tasks.Task<Examen.WS_Reference.MostrarClientesResponse> MostrarClientesAsync(Examen.WS_Reference.MostrarClientesRequest request);
        
        // CODEGEN: Generating message contract since element name nombreLibro from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/creaLibro", ReplyAction="*")]
        Examen.WS_Reference.creaLibroResponse creaLibro(Examen.WS_Reference.creaLibroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/creaLibro", ReplyAction="*")]
        System.Threading.Tasks.Task<Examen.WS_Reference.creaLibroResponse> creaLibroAsync(Examen.WS_Reference.creaLibroRequest request);
        
        // CODEGEN: Generating message contract since element name NameEditLibro from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/editaLibro", ReplyAction="*")]
        Examen.WS_Reference.editaLibroResponse editaLibro(Examen.WS_Reference.editaLibroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/editaLibro", ReplyAction="*")]
        System.Threading.Tasks.Task<Examen.WS_Reference.editaLibroResponse> editaLibroAsync(Examen.WS_Reference.editaLibroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminaLibro", ReplyAction="*")]
        bool eliminaLibro(int idLibro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminaLibro", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> eliminaLibroAsync(int idLibro);
        
        // CODEGEN: Generating message contract since element name MostrarLibroResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MostrarLibro", ReplyAction="*")]
        Examen.WS_Reference.MostrarLibroResponse MostrarLibro(Examen.WS_Reference.MostrarLibroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MostrarLibro", ReplyAction="*")]
        System.Threading.Tasks.Task<Examen.WS_Reference.MostrarLibroResponse> MostrarLibroAsync(Examen.WS_Reference.MostrarLibroRequest request);
        
        // CODEGEN: Generating message contract since element name MostrarPrestamosResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MostrarPrestamos", ReplyAction="*")]
        Examen.WS_Reference.MostrarPrestamosResponse MostrarPrestamos(Examen.WS_Reference.MostrarPrestamosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MostrarPrestamos", ReplyAction="*")]
        System.Threading.Tasks.Task<Examen.WS_Reference.MostrarPrestamosResponse> MostrarPrestamosAsync(Examen.WS_Reference.MostrarPrestamosRequest request);
        
        // CODEGEN: Generating message contract since element name MostrarDevolucionesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MostrarDevoluciones", ReplyAction="*")]
        Examen.WS_Reference.MostrarDevolucionesResponse MostrarDevoluciones(Examen.WS_Reference.MostrarDevolucionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MostrarDevoluciones", ReplyAction="*")]
        System.Threading.Tasks.Task<Examen.WS_Reference.MostrarDevolucionesResponse> MostrarDevolucionesAsync(Examen.WS_Reference.MostrarDevolucionesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class creaClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="creaCliente", Namespace="http://tempuri.org/", Order=0)]
        public Examen.WS_Reference.creaClienteRequestBody Body;
        
        public creaClienteRequest() {
        }
        
        public creaClienteRequest(Examen.WS_Reference.creaClienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class creaClienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string apellido;
        
        public creaClienteRequestBody() {
        }
        
        public creaClienteRequestBody(string nombre, string apellido) {
            this.nombre = nombre;
            this.apellido = apellido;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class creaClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="creaClienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public Examen.WS_Reference.creaClienteResponseBody Body;
        
        public creaClienteResponse() {
        }
        
        public creaClienteResponse(Examen.WS_Reference.creaClienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class creaClienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool creaClienteResult;
        
        public creaClienteResponseBody() {
        }
        
        public creaClienteResponseBody(bool creaClienteResult) {
            this.creaClienteResult = creaClienteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class editaClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="editaCliente", Namespace="http://tempuri.org/", Order=0)]
        public Examen.WS_Reference.editaClienteRequestBody Body;
        
        public editaClienteRequest() {
        }
        
        public editaClienteRequest(Examen.WS_Reference.editaClienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class editaClienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string NameEdit;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LastEdit;
        
        public editaClienteRequestBody() {
        }
        
        public editaClienteRequestBody(int idUser, string NameEdit, string LastEdit) {
            this.idUser = idUser;
            this.NameEdit = NameEdit;
            this.LastEdit = LastEdit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class editaClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="editaClienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public Examen.WS_Reference.editaClienteResponseBody Body;
        
        public editaClienteResponse() {
        }
        
        public editaClienteResponse(Examen.WS_Reference.editaClienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class editaClienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool editaClienteResult;
        
        public editaClienteResponseBody() {
        }
        
        public editaClienteResponseBody(bool editaClienteResult) {
            this.editaClienteResult = editaClienteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MostrarClientesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MostrarClientes", Namespace="http://tempuri.org/", Order=0)]
        public Examen.WS_Reference.MostrarClientesRequestBody Body;
        
        public MostrarClientesRequest() {
        }
        
        public MostrarClientesRequest(Examen.WS_Reference.MostrarClientesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class MostrarClientesRequestBody {
        
        public MostrarClientesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MostrarClientesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MostrarClientesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Examen.WS_Reference.MostrarClientesResponseBody Body;
        
        public MostrarClientesResponse() {
        }
        
        public MostrarClientesResponse(Examen.WS_Reference.MostrarClientesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MostrarClientesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Examen.WS_Reference.ListaClienteResult[] MostrarClientesResult;
        
        public MostrarClientesResponseBody() {
        }
        
        public MostrarClientesResponseBody(Examen.WS_Reference.ListaClienteResult[] MostrarClientesResult) {
            this.MostrarClientesResult = MostrarClientesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class creaLibroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="creaLibro", Namespace="http://tempuri.org/", Order=0)]
        public Examen.WS_Reference.creaLibroRequestBody Body;
        
        public creaLibroRequest() {
        }
        
        public creaLibroRequest(Examen.WS_Reference.creaLibroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class creaLibroRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombreLibro;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string autorLibro;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string annoLibro;
        
        public creaLibroRequestBody() {
        }
        
        public creaLibroRequestBody(string nombreLibro, string autorLibro, string annoLibro) {
            this.nombreLibro = nombreLibro;
            this.autorLibro = autorLibro;
            this.annoLibro = annoLibro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class creaLibroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="creaLibroResponse", Namespace="http://tempuri.org/", Order=0)]
        public Examen.WS_Reference.creaLibroResponseBody Body;
        
        public creaLibroResponse() {
        }
        
        public creaLibroResponse(Examen.WS_Reference.creaLibroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class creaLibroResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool creaLibroResult;
        
        public creaLibroResponseBody() {
        }
        
        public creaLibroResponseBody(bool creaLibroResult) {
            this.creaLibroResult = creaLibroResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class editaLibroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="editaLibro", Namespace="http://tempuri.org/", Order=0)]
        public Examen.WS_Reference.editaLibroRequestBody Body;
        
        public editaLibroRequest() {
        }
        
        public editaLibroRequest(Examen.WS_Reference.editaLibroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class editaLibroRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idLibro;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string NameEditLibro;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string autorEditLibro;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string annoEditLibro;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int estadoEditLibro;
        
        public editaLibroRequestBody() {
        }
        
        public editaLibroRequestBody(int idLibro, string NameEditLibro, string autorEditLibro, string annoEditLibro, int estadoEditLibro) {
            this.idLibro = idLibro;
            this.NameEditLibro = NameEditLibro;
            this.autorEditLibro = autorEditLibro;
            this.annoEditLibro = annoEditLibro;
            this.estadoEditLibro = estadoEditLibro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class editaLibroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="editaLibroResponse", Namespace="http://tempuri.org/", Order=0)]
        public Examen.WS_Reference.editaLibroResponseBody Body;
        
        public editaLibroResponse() {
        }
        
        public editaLibroResponse(Examen.WS_Reference.editaLibroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class editaLibroResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool editaLibroResult;
        
        public editaLibroResponseBody() {
        }
        
        public editaLibroResponseBody(bool editaLibroResult) {
            this.editaLibroResult = editaLibroResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MostrarLibroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MostrarLibro", Namespace="http://tempuri.org/", Order=0)]
        public Examen.WS_Reference.MostrarLibroRequestBody Body;
        
        public MostrarLibroRequest() {
        }
        
        public MostrarLibroRequest(Examen.WS_Reference.MostrarLibroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class MostrarLibroRequestBody {
        
        public MostrarLibroRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MostrarLibroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MostrarLibroResponse", Namespace="http://tempuri.org/", Order=0)]
        public Examen.WS_Reference.MostrarLibroResponseBody Body;
        
        public MostrarLibroResponse() {
        }
        
        public MostrarLibroResponse(Examen.WS_Reference.MostrarLibroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MostrarLibroResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Examen.WS_Reference.ListaLibroResult[] MostrarLibroResult;
        
        public MostrarLibroResponseBody() {
        }
        
        public MostrarLibroResponseBody(Examen.WS_Reference.ListaLibroResult[] MostrarLibroResult) {
            this.MostrarLibroResult = MostrarLibroResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MostrarPrestamosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MostrarPrestamos", Namespace="http://tempuri.org/", Order=0)]
        public Examen.WS_Reference.MostrarPrestamosRequestBody Body;
        
        public MostrarPrestamosRequest() {
        }
        
        public MostrarPrestamosRequest(Examen.WS_Reference.MostrarPrestamosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class MostrarPrestamosRequestBody {
        
        public MostrarPrestamosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MostrarPrestamosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MostrarPrestamosResponse", Namespace="http://tempuri.org/", Order=0)]
        public Examen.WS_Reference.MostrarPrestamosResponseBody Body;
        
        public MostrarPrestamosResponse() {
        }
        
        public MostrarPrestamosResponse(Examen.WS_Reference.MostrarPrestamosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MostrarPrestamosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Examen.WS_Reference.ListaPrestamosResult[] MostrarPrestamosResult;
        
        public MostrarPrestamosResponseBody() {
        }
        
        public MostrarPrestamosResponseBody(Examen.WS_Reference.ListaPrestamosResult[] MostrarPrestamosResult) {
            this.MostrarPrestamosResult = MostrarPrestamosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MostrarDevolucionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MostrarDevoluciones", Namespace="http://tempuri.org/", Order=0)]
        public Examen.WS_Reference.MostrarDevolucionesRequestBody Body;
        
        public MostrarDevolucionesRequest() {
        }
        
        public MostrarDevolucionesRequest(Examen.WS_Reference.MostrarDevolucionesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class MostrarDevolucionesRequestBody {
        
        public MostrarDevolucionesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MostrarDevolucionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MostrarDevolucionesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Examen.WS_Reference.MostrarDevolucionesResponseBody Body;
        
        public MostrarDevolucionesResponse() {
        }
        
        public MostrarDevolucionesResponse(Examen.WS_Reference.MostrarDevolucionesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MostrarDevolucionesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Examen.WS_Reference.ListaDevolucionesResult[] MostrarDevolucionesResult;
        
        public MostrarDevolucionesResponseBody() {
        }
        
        public MostrarDevolucionesResponseBody(Examen.WS_Reference.ListaDevolucionesResult[] MostrarDevolucionesResult) {
            this.MostrarDevolucionesResult = MostrarDevolucionesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSSoapChannel : Examen.WS_Reference.WSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSSoapClient : System.ServiceModel.ClientBase<Examen.WS_Reference.WSSoap>, Examen.WS_Reference.WSSoap {
        
        public WSSoapClient() {
        }
        
        public WSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Examen.WS_Reference.creaClienteResponse Examen.WS_Reference.WSSoap.creaCliente(Examen.WS_Reference.creaClienteRequest request) {
            return base.Channel.creaCliente(request);
        }
        
        public bool creaCliente(string nombre, string apellido) {
            Examen.WS_Reference.creaClienteRequest inValue = new Examen.WS_Reference.creaClienteRequest();
            inValue.Body = new Examen.WS_Reference.creaClienteRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.apellido = apellido;
            Examen.WS_Reference.creaClienteResponse retVal = ((Examen.WS_Reference.WSSoap)(this)).creaCliente(inValue);
            return retVal.Body.creaClienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Examen.WS_Reference.creaClienteResponse> Examen.WS_Reference.WSSoap.creaClienteAsync(Examen.WS_Reference.creaClienteRequest request) {
            return base.Channel.creaClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Examen.WS_Reference.creaClienteResponse> creaClienteAsync(string nombre, string apellido) {
            Examen.WS_Reference.creaClienteRequest inValue = new Examen.WS_Reference.creaClienteRequest();
            inValue.Body = new Examen.WS_Reference.creaClienteRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.apellido = apellido;
            return ((Examen.WS_Reference.WSSoap)(this)).creaClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Examen.WS_Reference.editaClienteResponse Examen.WS_Reference.WSSoap.editaCliente(Examen.WS_Reference.editaClienteRequest request) {
            return base.Channel.editaCliente(request);
        }
        
        public bool editaCliente(int idUser, string NameEdit, string LastEdit) {
            Examen.WS_Reference.editaClienteRequest inValue = new Examen.WS_Reference.editaClienteRequest();
            inValue.Body = new Examen.WS_Reference.editaClienteRequestBody();
            inValue.Body.idUser = idUser;
            inValue.Body.NameEdit = NameEdit;
            inValue.Body.LastEdit = LastEdit;
            Examen.WS_Reference.editaClienteResponse retVal = ((Examen.WS_Reference.WSSoap)(this)).editaCliente(inValue);
            return retVal.Body.editaClienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Examen.WS_Reference.editaClienteResponse> Examen.WS_Reference.WSSoap.editaClienteAsync(Examen.WS_Reference.editaClienteRequest request) {
            return base.Channel.editaClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Examen.WS_Reference.editaClienteResponse> editaClienteAsync(int idUser, string NameEdit, string LastEdit) {
            Examen.WS_Reference.editaClienteRequest inValue = new Examen.WS_Reference.editaClienteRequest();
            inValue.Body = new Examen.WS_Reference.editaClienteRequestBody();
            inValue.Body.idUser = idUser;
            inValue.Body.NameEdit = NameEdit;
            inValue.Body.LastEdit = LastEdit;
            return ((Examen.WS_Reference.WSSoap)(this)).editaClienteAsync(inValue);
        }
        
        public bool eliminaCliente(int idCliente) {
            return base.Channel.eliminaCliente(idCliente);
        }
        
        public System.Threading.Tasks.Task<bool> eliminaClienteAsync(int idCliente) {
            return base.Channel.eliminaClienteAsync(idCliente);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Examen.WS_Reference.MostrarClientesResponse Examen.WS_Reference.WSSoap.MostrarClientes(Examen.WS_Reference.MostrarClientesRequest request) {
            return base.Channel.MostrarClientes(request);
        }
        
        public Examen.WS_Reference.ListaClienteResult[] MostrarClientes() {
            Examen.WS_Reference.MostrarClientesRequest inValue = new Examen.WS_Reference.MostrarClientesRequest();
            inValue.Body = new Examen.WS_Reference.MostrarClientesRequestBody();
            Examen.WS_Reference.MostrarClientesResponse retVal = ((Examen.WS_Reference.WSSoap)(this)).MostrarClientes(inValue);
            return retVal.Body.MostrarClientesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Examen.WS_Reference.MostrarClientesResponse> Examen.WS_Reference.WSSoap.MostrarClientesAsync(Examen.WS_Reference.MostrarClientesRequest request) {
            return base.Channel.MostrarClientesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Examen.WS_Reference.MostrarClientesResponse> MostrarClientesAsync() {
            Examen.WS_Reference.MostrarClientesRequest inValue = new Examen.WS_Reference.MostrarClientesRequest();
            inValue.Body = new Examen.WS_Reference.MostrarClientesRequestBody();
            return ((Examen.WS_Reference.WSSoap)(this)).MostrarClientesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Examen.WS_Reference.creaLibroResponse Examen.WS_Reference.WSSoap.creaLibro(Examen.WS_Reference.creaLibroRequest request) {
            return base.Channel.creaLibro(request);
        }
        
        public bool creaLibro(string nombreLibro, string autorLibro, string annoLibro) {
            Examen.WS_Reference.creaLibroRequest inValue = new Examen.WS_Reference.creaLibroRequest();
            inValue.Body = new Examen.WS_Reference.creaLibroRequestBody();
            inValue.Body.nombreLibro = nombreLibro;
            inValue.Body.autorLibro = autorLibro;
            inValue.Body.annoLibro = annoLibro;
            Examen.WS_Reference.creaLibroResponse retVal = ((Examen.WS_Reference.WSSoap)(this)).creaLibro(inValue);
            return retVal.Body.creaLibroResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Examen.WS_Reference.creaLibroResponse> Examen.WS_Reference.WSSoap.creaLibroAsync(Examen.WS_Reference.creaLibroRequest request) {
            return base.Channel.creaLibroAsync(request);
        }
        
        public System.Threading.Tasks.Task<Examen.WS_Reference.creaLibroResponse> creaLibroAsync(string nombreLibro, string autorLibro, string annoLibro) {
            Examen.WS_Reference.creaLibroRequest inValue = new Examen.WS_Reference.creaLibroRequest();
            inValue.Body = new Examen.WS_Reference.creaLibroRequestBody();
            inValue.Body.nombreLibro = nombreLibro;
            inValue.Body.autorLibro = autorLibro;
            inValue.Body.annoLibro = annoLibro;
            return ((Examen.WS_Reference.WSSoap)(this)).creaLibroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Examen.WS_Reference.editaLibroResponse Examen.WS_Reference.WSSoap.editaLibro(Examen.WS_Reference.editaLibroRequest request) {
            return base.Channel.editaLibro(request);
        }
        
        public bool editaLibro(int idLibro, string NameEditLibro, string autorEditLibro, string annoEditLibro, int estadoEditLibro) {
            Examen.WS_Reference.editaLibroRequest inValue = new Examen.WS_Reference.editaLibroRequest();
            inValue.Body = new Examen.WS_Reference.editaLibroRequestBody();
            inValue.Body.idLibro = idLibro;
            inValue.Body.NameEditLibro = NameEditLibro;
            inValue.Body.autorEditLibro = autorEditLibro;
            inValue.Body.annoEditLibro = annoEditLibro;
            inValue.Body.estadoEditLibro = estadoEditLibro;
            Examen.WS_Reference.editaLibroResponse retVal = ((Examen.WS_Reference.WSSoap)(this)).editaLibro(inValue);
            return retVal.Body.editaLibroResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Examen.WS_Reference.editaLibroResponse> Examen.WS_Reference.WSSoap.editaLibroAsync(Examen.WS_Reference.editaLibroRequest request) {
            return base.Channel.editaLibroAsync(request);
        }
        
        public System.Threading.Tasks.Task<Examen.WS_Reference.editaLibroResponse> editaLibroAsync(int idLibro, string NameEditLibro, string autorEditLibro, string annoEditLibro, int estadoEditLibro) {
            Examen.WS_Reference.editaLibroRequest inValue = new Examen.WS_Reference.editaLibroRequest();
            inValue.Body = new Examen.WS_Reference.editaLibroRequestBody();
            inValue.Body.idLibro = idLibro;
            inValue.Body.NameEditLibro = NameEditLibro;
            inValue.Body.autorEditLibro = autorEditLibro;
            inValue.Body.annoEditLibro = annoEditLibro;
            inValue.Body.estadoEditLibro = estadoEditLibro;
            return ((Examen.WS_Reference.WSSoap)(this)).editaLibroAsync(inValue);
        }
        
        public bool eliminaLibro(int idLibro) {
            return base.Channel.eliminaLibro(idLibro);
        }
        
        public System.Threading.Tasks.Task<bool> eliminaLibroAsync(int idLibro) {
            return base.Channel.eliminaLibroAsync(idLibro);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Examen.WS_Reference.MostrarLibroResponse Examen.WS_Reference.WSSoap.MostrarLibro(Examen.WS_Reference.MostrarLibroRequest request) {
            return base.Channel.MostrarLibro(request);
        }
        
        public Examen.WS_Reference.ListaLibroResult[] MostrarLibro() {
            Examen.WS_Reference.MostrarLibroRequest inValue = new Examen.WS_Reference.MostrarLibroRequest();
            inValue.Body = new Examen.WS_Reference.MostrarLibroRequestBody();
            Examen.WS_Reference.MostrarLibroResponse retVal = ((Examen.WS_Reference.WSSoap)(this)).MostrarLibro(inValue);
            return retVal.Body.MostrarLibroResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Examen.WS_Reference.MostrarLibroResponse> Examen.WS_Reference.WSSoap.MostrarLibroAsync(Examen.WS_Reference.MostrarLibroRequest request) {
            return base.Channel.MostrarLibroAsync(request);
        }
        
        public System.Threading.Tasks.Task<Examen.WS_Reference.MostrarLibroResponse> MostrarLibroAsync() {
            Examen.WS_Reference.MostrarLibroRequest inValue = new Examen.WS_Reference.MostrarLibroRequest();
            inValue.Body = new Examen.WS_Reference.MostrarLibroRequestBody();
            return ((Examen.WS_Reference.WSSoap)(this)).MostrarLibroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Examen.WS_Reference.MostrarPrestamosResponse Examen.WS_Reference.WSSoap.MostrarPrestamos(Examen.WS_Reference.MostrarPrestamosRequest request) {
            return base.Channel.MostrarPrestamos(request);
        }
        
        public Examen.WS_Reference.ListaPrestamosResult[] MostrarPrestamos() {
            Examen.WS_Reference.MostrarPrestamosRequest inValue = new Examen.WS_Reference.MostrarPrestamosRequest();
            inValue.Body = new Examen.WS_Reference.MostrarPrestamosRequestBody();
            Examen.WS_Reference.MostrarPrestamosResponse retVal = ((Examen.WS_Reference.WSSoap)(this)).MostrarPrestamos(inValue);
            return retVal.Body.MostrarPrestamosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Examen.WS_Reference.MostrarPrestamosResponse> Examen.WS_Reference.WSSoap.MostrarPrestamosAsync(Examen.WS_Reference.MostrarPrestamosRequest request) {
            return base.Channel.MostrarPrestamosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Examen.WS_Reference.MostrarPrestamosResponse> MostrarPrestamosAsync() {
            Examen.WS_Reference.MostrarPrestamosRequest inValue = new Examen.WS_Reference.MostrarPrestamosRequest();
            inValue.Body = new Examen.WS_Reference.MostrarPrestamosRequestBody();
            return ((Examen.WS_Reference.WSSoap)(this)).MostrarPrestamosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Examen.WS_Reference.MostrarDevolucionesResponse Examen.WS_Reference.WSSoap.MostrarDevoluciones(Examen.WS_Reference.MostrarDevolucionesRequest request) {
            return base.Channel.MostrarDevoluciones(request);
        }
        
        public Examen.WS_Reference.ListaDevolucionesResult[] MostrarDevoluciones() {
            Examen.WS_Reference.MostrarDevolucionesRequest inValue = new Examen.WS_Reference.MostrarDevolucionesRequest();
            inValue.Body = new Examen.WS_Reference.MostrarDevolucionesRequestBody();
            Examen.WS_Reference.MostrarDevolucionesResponse retVal = ((Examen.WS_Reference.WSSoap)(this)).MostrarDevoluciones(inValue);
            return retVal.Body.MostrarDevolucionesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Examen.WS_Reference.MostrarDevolucionesResponse> Examen.WS_Reference.WSSoap.MostrarDevolucionesAsync(Examen.WS_Reference.MostrarDevolucionesRequest request) {
            return base.Channel.MostrarDevolucionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Examen.WS_Reference.MostrarDevolucionesResponse> MostrarDevolucionesAsync() {
            Examen.WS_Reference.MostrarDevolucionesRequest inValue = new Examen.WS_Reference.MostrarDevolucionesRequest();
            inValue.Body = new Examen.WS_Reference.MostrarDevolucionesRequestBody();
            return ((Examen.WS_Reference.WSSoap)(this)).MostrarDevolucionesAsync(inValue);
        }
    }
}
