//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen.WSJAVA {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WS/", ConfigurationName="WSJAVA.WSJAVA")]
    public interface WSJAVA {
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://WS/)
        [System.ServiceModel.OperationContractAttribute(Action="http://WS/WSJAVA/eliminaUserRequest", ReplyAction="http://WS/WSJAVA/eliminaUserResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Examen.WSJAVA.eliminaUserResponse eliminaUser(Examen.WSJAVA.eliminaUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WS/WSJAVA/eliminaUserRequest", ReplyAction="http://WS/WSJAVA/eliminaUserResponse")]
        System.Threading.Tasks.Task<Examen.WSJAVA.eliminaUserResponse> eliminaUserAsync(Examen.WSJAVA.eliminaUserRequest request);
        
        // CODEGEN: Generating message contract since element name nameLibro from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://WS/WSJAVA/creaLibroRequest", ReplyAction="http://WS/WSJAVA/creaLibroResponse")]
        Examen.WSJAVA.creaLibroResponse creaLibro(Examen.WSJAVA.creaLibroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WS/WSJAVA/creaLibroRequest", ReplyAction="http://WS/WSJAVA/creaLibroResponse")]
        System.Threading.Tasks.Task<Examen.WSJAVA.creaLibroResponse> creaLibroAsync(Examen.WSJAVA.creaLibroRequest request);
        
        // CODEGEN: Generating message contract since element name nameUser from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://WS/WSJAVA/creaUsuarioRequest", ReplyAction="http://WS/WSJAVA/creaUsuarioResponse")]
        Examen.WSJAVA.creaUsuarioResponse creaUsuario(Examen.WSJAVA.creaUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WS/WSJAVA/creaUsuarioRequest", ReplyAction="http://WS/WSJAVA/creaUsuarioResponse")]
        System.Threading.Tasks.Task<Examen.WSJAVA.creaUsuarioResponse> creaUsuarioAsync(Examen.WSJAVA.creaUsuarioRequest request);
        
        // CODEGEN: Generating message contract since element name nameUserEdit from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://WS/WSJAVA/editaUserRequest", ReplyAction="http://WS/WSJAVA/editaUserResponse")]
        Examen.WSJAVA.editaUserResponse editaUser(Examen.WSJAVA.editaUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WS/WSJAVA/editaUserRequest", ReplyAction="http://WS/WSJAVA/editaUserResponse")]
        System.Threading.Tasks.Task<Examen.WSJAVA.editaUserResponse> editaUserAsync(Examen.WSJAVA.editaUserRequest request);
        
        // CODEGEN: Generating message contract since element name nameLibroEdit from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://WS/WSJAVA/editaLibroRequest", ReplyAction="http://WS/WSJAVA/editaLibroResponse")]
        Examen.WSJAVA.editaLibroResponse editaLibro(Examen.WSJAVA.editaLibroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WS/WSJAVA/editaLibroRequest", ReplyAction="http://WS/WSJAVA/editaLibroResponse")]
        System.Threading.Tasks.Task<Examen.WSJAVA.editaLibroResponse> editaLibroAsync(Examen.WSJAVA.editaLibroRequest request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://WS/)
        [System.ServiceModel.OperationContractAttribute(Action="http://WS/WSJAVA/eliminaLibroRequest", ReplyAction="http://WS/WSJAVA/eliminaLibroResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Examen.WSJAVA.eliminaLibroResponse eliminaLibro(Examen.WSJAVA.eliminaLibroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WS/WSJAVA/eliminaLibroRequest", ReplyAction="http://WS/WSJAVA/eliminaLibroResponse")]
        System.Threading.Tasks.Task<Examen.WSJAVA.eliminaLibroResponse> eliminaLibroAsync(Examen.WSJAVA.eliminaLibroRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminaUser", WrapperNamespace="http://WS/", IsWrapped=true)]
    public partial class eliminaUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int idUserDelete;
        
        public eliminaUserRequest() {
        }
        
        public eliminaUserRequest(int idUserDelete) {
            this.idUserDelete = idUserDelete;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminaUserResponse", WrapperNamespace="http://WS/", IsWrapped=true)]
    public partial class eliminaUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool @return;
        
        public eliminaUserResponse() {
        }
        
        public eliminaUserResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class creaLibroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="creaLibro", Namespace="http://WS/", Order=0)]
        public Examen.WSJAVA.creaLibroRequestBody Body;
        
        public creaLibroRequest() {
        }
        
        public creaLibroRequest(Examen.WSJAVA.creaLibroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class creaLibroRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nameLibro;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string autorLibro;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string annoLibro;
        
        public creaLibroRequestBody() {
        }
        
        public creaLibroRequestBody(string nameLibro, string autorLibro, string annoLibro) {
            this.nameLibro = nameLibro;
            this.autorLibro = autorLibro;
            this.annoLibro = annoLibro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class creaLibroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="creaLibroResponse", Namespace="http://WS/", Order=0)]
        public Examen.WSJAVA.creaLibroResponseBody Body;
        
        public creaLibroResponse() {
        }
        
        public creaLibroResponse(Examen.WSJAVA.creaLibroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class creaLibroResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public creaLibroResponseBody() {
        }
        
        public creaLibroResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class creaUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="creaUsuario", Namespace="http://WS/", Order=0)]
        public Examen.WSJAVA.creaUsuarioRequestBody Body;
        
        public creaUsuarioRequest() {
        }
        
        public creaUsuarioRequest(Examen.WSJAVA.creaUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class creaUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nameUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string lastUser;
        
        public creaUsuarioRequestBody() {
        }
        
        public creaUsuarioRequestBody(string nameUser, string lastUser) {
            this.nameUser = nameUser;
            this.lastUser = lastUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class creaUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="creaUsuarioResponse", Namespace="http://WS/", Order=0)]
        public Examen.WSJAVA.creaUsuarioResponseBody Body;
        
        public creaUsuarioResponse() {
        }
        
        public creaUsuarioResponse(Examen.WSJAVA.creaUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class creaUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public creaUsuarioResponseBody() {
        }
        
        public creaUsuarioResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class editaUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="editaUser", Namespace="http://WS/", Order=0)]
        public Examen.WSJAVA.editaUserRequestBody Body;
        
        public editaUserRequest() {
        }
        
        public editaUserRequest(Examen.WSJAVA.editaUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class editaUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idUserEdit;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nameUserEdit;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lastUserEdit;
        
        public editaUserRequestBody() {
        }
        
        public editaUserRequestBody(int idUserEdit, string nameUserEdit, string lastUserEdit) {
            this.idUserEdit = idUserEdit;
            this.nameUserEdit = nameUserEdit;
            this.lastUserEdit = lastUserEdit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class editaUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="editaUserResponse", Namespace="http://WS/", Order=0)]
        public Examen.WSJAVA.editaUserResponseBody Body;
        
        public editaUserResponse() {
        }
        
        public editaUserResponse(Examen.WSJAVA.editaUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class editaUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public editaUserResponseBody() {
        }
        
        public editaUserResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class editaLibroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="editaLibro", Namespace="http://WS/", Order=0)]
        public Examen.WSJAVA.editaLibroRequestBody Body;
        
        public editaLibroRequest() {
        }
        
        public editaLibroRequest(Examen.WSJAVA.editaLibroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class editaLibroRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idLibroEdit;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nameLibroEdit;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string autorLibroEdit;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string annoLibroEdit;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int estadoLibroEdit;
        
        public editaLibroRequestBody() {
        }
        
        public editaLibroRequestBody(int idLibroEdit, string nameLibroEdit, string autorLibroEdit, string annoLibroEdit, int estadoLibroEdit) {
            this.idLibroEdit = idLibroEdit;
            this.nameLibroEdit = nameLibroEdit;
            this.autorLibroEdit = autorLibroEdit;
            this.annoLibroEdit = annoLibroEdit;
            this.estadoLibroEdit = estadoLibroEdit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class editaLibroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="editaLibroResponse", Namespace="http://WS/", Order=0)]
        public Examen.WSJAVA.editaLibroResponseBody Body;
        
        public editaLibroResponse() {
        }
        
        public editaLibroResponse(Examen.WSJAVA.editaLibroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class editaLibroResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public editaLibroResponseBody() {
        }
        
        public editaLibroResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminaLibro", WrapperNamespace="http://WS/", IsWrapped=true)]
    public partial class eliminaLibroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int idLibroDelete;
        
        public eliminaLibroRequest() {
        }
        
        public eliminaLibroRequest(int idLibroDelete) {
            this.idLibroDelete = idLibroDelete;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminaLibroResponse", WrapperNamespace="http://WS/", IsWrapped=true)]
    public partial class eliminaLibroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool @return;
        
        public eliminaLibroResponse() {
        }
        
        public eliminaLibroResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSJAVAChannel : Examen.WSJAVA.WSJAVA, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSJAVAClient : System.ServiceModel.ClientBase<Examen.WSJAVA.WSJAVA>, Examen.WSJAVA.WSJAVA {
        
        public WSJAVAClient() {
        }
        
        public WSJAVAClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSJAVAClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSJAVAClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSJAVAClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Examen.WSJAVA.eliminaUserResponse Examen.WSJAVA.WSJAVA.eliminaUser(Examen.WSJAVA.eliminaUserRequest request) {
            return base.Channel.eliminaUser(request);
        }
        
        public bool eliminaUser(int idUserDelete) {
            Examen.WSJAVA.eliminaUserRequest inValue = new Examen.WSJAVA.eliminaUserRequest();
            inValue.idUserDelete = idUserDelete;
            Examen.WSJAVA.eliminaUserResponse retVal = ((Examen.WSJAVA.WSJAVA)(this)).eliminaUser(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Examen.WSJAVA.eliminaUserResponse> Examen.WSJAVA.WSJAVA.eliminaUserAsync(Examen.WSJAVA.eliminaUserRequest request) {
            return base.Channel.eliminaUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<Examen.WSJAVA.eliminaUserResponse> eliminaUserAsync(int idUserDelete) {
            Examen.WSJAVA.eliminaUserRequest inValue = new Examen.WSJAVA.eliminaUserRequest();
            inValue.idUserDelete = idUserDelete;
            return ((Examen.WSJAVA.WSJAVA)(this)).eliminaUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Examen.WSJAVA.creaLibroResponse Examen.WSJAVA.WSJAVA.creaLibro(Examen.WSJAVA.creaLibroRequest request) {
            return base.Channel.creaLibro(request);
        }
        
        public bool creaLibro(string nameLibro, string autorLibro, string annoLibro) {
            Examen.WSJAVA.creaLibroRequest inValue = new Examen.WSJAVA.creaLibroRequest();
            inValue.Body = new Examen.WSJAVA.creaLibroRequestBody();
            inValue.Body.nameLibro = nameLibro;
            inValue.Body.autorLibro = autorLibro;
            inValue.Body.annoLibro = annoLibro;
            Examen.WSJAVA.creaLibroResponse retVal = ((Examen.WSJAVA.WSJAVA)(this)).creaLibro(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Examen.WSJAVA.creaLibroResponse> Examen.WSJAVA.WSJAVA.creaLibroAsync(Examen.WSJAVA.creaLibroRequest request) {
            return base.Channel.creaLibroAsync(request);
        }
        
        public System.Threading.Tasks.Task<Examen.WSJAVA.creaLibroResponse> creaLibroAsync(string nameLibro, string autorLibro, string annoLibro) {
            Examen.WSJAVA.creaLibroRequest inValue = new Examen.WSJAVA.creaLibroRequest();
            inValue.Body = new Examen.WSJAVA.creaLibroRequestBody();
            inValue.Body.nameLibro = nameLibro;
            inValue.Body.autorLibro = autorLibro;
            inValue.Body.annoLibro = annoLibro;
            return ((Examen.WSJAVA.WSJAVA)(this)).creaLibroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Examen.WSJAVA.creaUsuarioResponse Examen.WSJAVA.WSJAVA.creaUsuario(Examen.WSJAVA.creaUsuarioRequest request) {
            return base.Channel.creaUsuario(request);
        }
        
        public bool creaUsuario(string nameUser, string lastUser) {
            Examen.WSJAVA.creaUsuarioRequest inValue = new Examen.WSJAVA.creaUsuarioRequest();
            inValue.Body = new Examen.WSJAVA.creaUsuarioRequestBody();
            inValue.Body.nameUser = nameUser;
            inValue.Body.lastUser = lastUser;
            Examen.WSJAVA.creaUsuarioResponse retVal = ((Examen.WSJAVA.WSJAVA)(this)).creaUsuario(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Examen.WSJAVA.creaUsuarioResponse> Examen.WSJAVA.WSJAVA.creaUsuarioAsync(Examen.WSJAVA.creaUsuarioRequest request) {
            return base.Channel.creaUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<Examen.WSJAVA.creaUsuarioResponse> creaUsuarioAsync(string nameUser, string lastUser) {
            Examen.WSJAVA.creaUsuarioRequest inValue = new Examen.WSJAVA.creaUsuarioRequest();
            inValue.Body = new Examen.WSJAVA.creaUsuarioRequestBody();
            inValue.Body.nameUser = nameUser;
            inValue.Body.lastUser = lastUser;
            return ((Examen.WSJAVA.WSJAVA)(this)).creaUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Examen.WSJAVA.editaUserResponse Examen.WSJAVA.WSJAVA.editaUser(Examen.WSJAVA.editaUserRequest request) {
            return base.Channel.editaUser(request);
        }
        
        public bool editaUser(int idUserEdit, string nameUserEdit, string lastUserEdit) {
            Examen.WSJAVA.editaUserRequest inValue = new Examen.WSJAVA.editaUserRequest();
            inValue.Body = new Examen.WSJAVA.editaUserRequestBody();
            inValue.Body.idUserEdit = idUserEdit;
            inValue.Body.nameUserEdit = nameUserEdit;
            inValue.Body.lastUserEdit = lastUserEdit;
            Examen.WSJAVA.editaUserResponse retVal = ((Examen.WSJAVA.WSJAVA)(this)).editaUser(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Examen.WSJAVA.editaUserResponse> Examen.WSJAVA.WSJAVA.editaUserAsync(Examen.WSJAVA.editaUserRequest request) {
            return base.Channel.editaUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<Examen.WSJAVA.editaUserResponse> editaUserAsync(int idUserEdit, string nameUserEdit, string lastUserEdit) {
            Examen.WSJAVA.editaUserRequest inValue = new Examen.WSJAVA.editaUserRequest();
            inValue.Body = new Examen.WSJAVA.editaUserRequestBody();
            inValue.Body.idUserEdit = idUserEdit;
            inValue.Body.nameUserEdit = nameUserEdit;
            inValue.Body.lastUserEdit = lastUserEdit;
            return ((Examen.WSJAVA.WSJAVA)(this)).editaUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Examen.WSJAVA.editaLibroResponse Examen.WSJAVA.WSJAVA.editaLibro(Examen.WSJAVA.editaLibroRequest request) {
            return base.Channel.editaLibro(request);
        }
        
        public bool editaLibro(int idLibroEdit, string nameLibroEdit, string autorLibroEdit, string annoLibroEdit, int estadoLibroEdit) {
            Examen.WSJAVA.editaLibroRequest inValue = new Examen.WSJAVA.editaLibroRequest();
            inValue.Body = new Examen.WSJAVA.editaLibroRequestBody();
            inValue.Body.idLibroEdit = idLibroEdit;
            inValue.Body.nameLibroEdit = nameLibroEdit;
            inValue.Body.autorLibroEdit = autorLibroEdit;
            inValue.Body.annoLibroEdit = annoLibroEdit;
            inValue.Body.estadoLibroEdit = estadoLibroEdit;
            Examen.WSJAVA.editaLibroResponse retVal = ((Examen.WSJAVA.WSJAVA)(this)).editaLibro(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Examen.WSJAVA.editaLibroResponse> Examen.WSJAVA.WSJAVA.editaLibroAsync(Examen.WSJAVA.editaLibroRequest request) {
            return base.Channel.editaLibroAsync(request);
        }
        
        public System.Threading.Tasks.Task<Examen.WSJAVA.editaLibroResponse> editaLibroAsync(int idLibroEdit, string nameLibroEdit, string autorLibroEdit, string annoLibroEdit, int estadoLibroEdit) {
            Examen.WSJAVA.editaLibroRequest inValue = new Examen.WSJAVA.editaLibroRequest();
            inValue.Body = new Examen.WSJAVA.editaLibroRequestBody();
            inValue.Body.idLibroEdit = idLibroEdit;
            inValue.Body.nameLibroEdit = nameLibroEdit;
            inValue.Body.autorLibroEdit = autorLibroEdit;
            inValue.Body.annoLibroEdit = annoLibroEdit;
            inValue.Body.estadoLibroEdit = estadoLibroEdit;
            return ((Examen.WSJAVA.WSJAVA)(this)).editaLibroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Examen.WSJAVA.eliminaLibroResponse Examen.WSJAVA.WSJAVA.eliminaLibro(Examen.WSJAVA.eliminaLibroRequest request) {
            return base.Channel.eliminaLibro(request);
        }
        
        public bool eliminaLibro(int idLibroDelete) {
            Examen.WSJAVA.eliminaLibroRequest inValue = new Examen.WSJAVA.eliminaLibroRequest();
            inValue.idLibroDelete = idLibroDelete;
            Examen.WSJAVA.eliminaLibroResponse retVal = ((Examen.WSJAVA.WSJAVA)(this)).eliminaLibro(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Examen.WSJAVA.eliminaLibroResponse> Examen.WSJAVA.WSJAVA.eliminaLibroAsync(Examen.WSJAVA.eliminaLibroRequest request) {
            return base.Channel.eliminaLibroAsync(request);
        }
        
        public System.Threading.Tasks.Task<Examen.WSJAVA.eliminaLibroResponse> eliminaLibroAsync(int idLibroDelete) {
            Examen.WSJAVA.eliminaLibroRequest inValue = new Examen.WSJAVA.eliminaLibroRequest();
            inValue.idLibroDelete = idLibroDelete;
            return ((Examen.WSJAVA.WSJAVA)(this)).eliminaLibroAsync(inValue);
        }
    }
}
